Eshop/Eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^', include('Home.urls', namespace='home')),
    url(r'^store/', include('store.urls', namespace='store')),
    url(r'^profile/', include('prof.urls', namespace='prof')),
]
handler404 = "Eshop.views.page_not_found_view"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Eshop/Home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as v_iews

app_name = 'Home'
urlpatterns = [
    path('', views.home, name='home'),
    path('contact', views.Contact, name='contact'),
    path('about/', views.about, name='about'),
    path('signup/', views.signup, name='signup'),
    path('login/', v_iews.LoginView.as_view(), name='login'),
    path('password_change/', v_iews.PasswordChangeView.as_view(), name='password_change'),
    path('password_change_done/', v_iews.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', v_iews.PasswordResetView.as_view(), name='password_reset'),
]

Eshop/prof/urls.py
from django.urls import path
from . import views

app_name = 'prof'

urlpatterns = [
    path('<slug>/', views.profile, name='profile'),
    path('<slug>/edit', views.edit_profile, name='edit_profile'),
]

Eshop/store/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from . import views

app_name = 'store'
urlpatterns = [
    url(r'^$', views.shop, name='menu'),
    path('product/<int:id>/', views.product, name='product'),
    path('category/<id>/', views.category, name='category'),
    path('cart/', views.cart, name='cart'),
    path('WishItems/', views.WishList, name='WishItems'),
    path('shipping/', views.shipping, name="shipping"),

    path('update_item/', views.updateItem, name="update_item"),
    path('add_to_wish_list/', views.addToWishList, name="addToWishList"),

    path('checkout/', views.checkout, name='checkout'),
    path('charge/', views.charge, name="charge"),
    path('success/<int:args>/', views.successMsg, name="success"),
    path('PaymentCompleted/', views.PaymentCompleted, name='PaymentCompleted')
]

Eshop/templates/base.html
{% load static %}
<!DOCTYPE html>
 <html lang="en">
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=Edge">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"> 
    <meta name="description" content="easy shop your own store for clothes and more products">
    <meta name="author" content="Abdljbbar Ait jeddi">
    <meta name="generator" content="Jekyll v3.8.5">
    {% block head %}
    {% endblock %}
    <title>{% block title %}Esay Shop {% endblock %}</title>
    <link rel="icon" href="{% static 'img/favicon.svg' %}">

    <link rel="stylesheet" href="{% static 'mdb/mdb.min.css' %}">
    <link rel="stylesheet" href="{% static 'style2.css' %}">
    <link rel="stylesheet" href="{% static 'res/semantic@2.4.2.css' %}">
    <link rel="stylesheet" href="{% static 'style1.css' %}">
    <link href="{% static 'fontawesomefree/css/fontawesome.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/brands.css' %}" rel="stylesheet" type="text/css">
    <link href="{% static 'fontawesomefree/css/solid.css' %}" rel="stylesheet" type="text/css">
<style type="text/css">
    <!-- custom styling for all icons -->
    i.fas,
    i.fab {
      border: 1px solid red;
    }
    <!-- custom styling for specific icons -->

    .fa-twitter {
      color: rgb(59, 91, 152);
    }

    .fa-facebook {
      color: rgb(59, 91, 152);
    }
    .fa-instagram {
      color: pink;
    }
    .form-control {
      outline: none;
    }
    .imggg21 {
         background-image: linear-gradient(to right bottom, #5734ca, #a178f8);
         background-position: center;
         background-size: 100% 100%;
         overflow-x: hidden;
    }
    .port{
        background: linear-gradient(to right bottom,
        rgba(152,205,237,0.5),
        rgba(170,201,167,0.3)
        );
        border-radius: 1rem;
        /*backdrop-filter: blur(2rem);
        z-index: 3;*/
        box-shadow: 0px 5px 5.5px 0px black;
    }
    #cart-icon{
        width:25px;
        display: inline-block;
    }
    .cart-icon{
        width:25px;
        display: inline-block;
    }
  </style>
<script>
var user = "{{request.user}}"
var url123 = "{% url 'store:update_item' %}"
function getToken(name) {
        var cookieValue = null;
        if (document.cookie && document.cookie !== '') {
                var cookies = document.cookie.split(';');
                for (var i = 0; i < cookies.length; i++) {
                        var cookie = cookies[i].trim();
                         // Does this cookie string begin with the name we want?
                         if (cookie.substring(0, name.length + 1) === (name + '=')) {
                                cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                                break;
                         }
                }
        }
        return cookieValue;
}
var csrftoken = getToken('csrftoken')

function getCookie(name) {
// Split cookie string and get all individual name=value pairs in an array
        var cookieArr = document.cookie.split(";");

        // Loop through the array elements
        for(var i = 0; i < cookieArr.length; i++) {
                var cookiePair = cookieArr[i].split("=");

                /* Removing whitespace at the beginning of the cookie name
                and compare it with the given string */
                if(name == cookiePair[0].trim()) {
                        // Decode the cookie value and return
                        return decodeURIComponent(cookiePair[1]);
                }
        }

                // Return null if not found
                        return null;
}
var cart = JSON.parse(getCookie('cart'))
        if (cart == undefined){
                cart = {}
                console.log('Cart Created!', cart)
                document.cookie ='cart=' + JSON.stringify(cart) + ";domain=;path=/"
        }
        console.log('Cart:', cart)
</script>
</head>

<body>

{% block content %}
{% endblock %}
<br>
<script src="{% static 'jquery.js' %}"></script>
<script src="{% static 'javascript.js' %}"></script>
<script src="{% static 'cart1.js' %}"></script>

<script src="{% static 'mdb/mdb.min.js' %}"></script>
 </body>
<html>

Eshop/templates/footer.html
<div class="ui inverted vertical footer segment">
      <div class="ui container">
        <div class="ui stackable inverted divided equal height stackable grid">
      <div class="three wide column">
            <h4 class="ui inverted header text-primary">About</h4>
            <div class="ui inverted link list">
              <a href="#" class="item">Sitemap</a> 
              <a href="#" class="item">Terms</a>       
              <a href="#" class="item">Privacy & Policy</a>
              <a href="#" class="item">Gazebo Plans</a>             
           </div>
        </div>                
              <div class="three wide column">
            <h4 class="ui inverted header text-primary">Contact Us</h4>
              <div class="ui inverted link list"> 
              <a href="#" class="item"><i class="fab fa-facebook"></i></a>
              <a href="https://twitter.com/Abdljbbar1/status/1433618511398678530?s=20" class="item"><i class="fab fa-twitter"></i></a>
              <a href="https://www.instagram.com/invites/contact/?i=1xu4tkg5bv6xo&utm_content=kbxtd2e" class="item"><i class="fab fa-instagram"></i></a>                
              <a href="https://github.com/frx-Abdljbbar-code" class="item"><i class="fab fa-github"></i></a>
            </div>
          </div>       
     <div class="three wide column">
      <h4 class="ui inverted header text-primary">Support</h4>
       <div class="ui inverted link list">
             <a href="#" class="item">Eshop Support</a>
             <a href="https://paypal.com" class="item">Paypal</a>
             <a href="https://stripe.com" class="item">Stripe</a>
             <a href="{% url 'home:contact' %}" class="item">Contact me</a>
         </div>
         </div>
          <div class="seven wide column">
            <h4 class="text-center ui inverted header text-primary">Easy shop</h4>
            <p class="text-center mb-1">&copy; All rights reserved Abdljbbar 2020-2021</p>
          </div>
        </div>
      </div>

Eshop/templates/navbar.html
{% load static %}
<!-- Navbar -->
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <!-- Container wrapper -->
  <div class="container-fluid">
    <!-- Toggle button -->
    <button style="height: 60px; width: 60px" class="navbar-toggler" type="button" data-mdb-toggle="collapse" data-mdb-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <img class="navbar-toggler-icon" src="{% static 'images/13.png' %}"><!--i class="fas fa-bars"></i-->
    </button>
    <h3 style="letter-spacing: 4px;margin-right: 50px;" class="text-secondary center">Eshop</h3>
    <!-- Collapsible wrapper -->
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <!-- Navbar brand -->
      <a class="navbar-brand mt-2 mt-lg-0" href="#">
        <img src="{% static 'img/favicon1.svg' %}" height="15" alt="" loading="lazy"/>
      </a>
      <!-- Left links -->
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link" href="{% url 'store:menu' %}">Store</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home:about' %}">About</a>
        </li>
        <li class="nav-item">
          <a class="nav-link" href="{% url 'home:contact' %}">Contact me</a>
        </li>
      </ul>
      <!-- Left links -->
    </div>
    <!-- Collapsible wrapper -->

    <!-- Right elements -->
    <div class="d-flex align-items-center">
      <!-- Icon -->
      <a class="text-reset me-3" href="{% url 'store:cart' %}">
        <i class="fas fa-shopping-cart"></i>
	{% if cartItems > 0 %}
        <span class="badge rounded-pill badge-notification bg-danger">{{cartItems}}</span>
	{% else %}

	{% endif %}
       </a>

      <!-- Notifications -->
     

      <!-- Avatar -->
  {% if user.is_authenticated %}
      <a class="dropdown-toggle d-flex align-items-center hidden-arrow" href="#" id="navbarDropdownMenuLink" role="button" data-mdb-toggle="dropdown" aria-expanded="false">
      {% if not user.profile.image %}
       <img src="{% static 'images/avatar.jpg' %}" class="rounded-circle" height="25" width="25" alt="profile" loading="lazy" />
      {% else %}
        <img src="{{ user.profile.image.url }}" class="rounded-circle" height="25" width="25" alt="profile" loading="lazy" />
      {% endif %}
      </a>
      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
        <li>
          <a class="dropdown-item" href="{% url 'prof:profile' slug=user.profile.slug %}">My profile</a>
        </li>
        <li>
          <a class="dropdown-item" href="{% url 'prof:edit_profile' slug=user.profile.slug %}">Edit profile</a>
        </li>
        <li>
          <a class="dropdown-item" href="{% url 'logout' %}">Logout</a>
        </li>
      </ul>
{% else %}
         <a class="dropdown-toggle d-flex align-items-center hidden-arrow" href="#" id="navbarDropdownMenuLink" role="button" data-mdb-toggle="dropdown" aria-expanded="false" >
        <img src="{% static 'images/11.png' %}" class="rounded-circle" height="25" alt="Profile" loading="lazy" />
      </a>
      <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdownMenuLink">
        <li>
          <a class="dropdown-item" href="{% url 'login' %}">Sign IN</a>
        </li>
        <li>
          <a class="dropdown-item" href="{% url 'home:signup' %}">Sign UP</a>
        </li>
      </ul>
  {% endif %}
</div>
    <!-- Right elements -->
  </div>
  <!-- Container wrapper -->
</div>
</nav>

<!-- Navbar -->

Eshop/templates/navbar1.html
{% load static %}
<nav class="navbar navbar-expand-md navbar-secondary bg-light">
    <a class="navbar-brand text-success two" href="/">E-Shop
       <img class="navbar-toggler-icon one" src="{% static 'img/favicon1.svg' %}">
    </a>
    <button class="bg-light navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
      <img class="navbar-toggler-icon" src="{% static 'images/13.png' %}">
    </button>
    <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul dir="ltr" class="navbar-nav mr-auto">
   {% if user.is_authenticated %}
              <li class="mav--item"><strong>
                 <a class="nav-link text-info" href="{% url 'prof:profile' slug=user.profile.slug %}">profile</a>
                </strong></li>
               <li class="mav--item"><strong>
                 <a class="nav-link text-danger" href="{% url 'logout' %}">logout</a>
               </strong></li>
    {% else %}
                <li class="mav--item"><strong>
                    <a class="nav-link text-info" href="{% url 'login' %}">login</a>
                </strong></li>
                <li class="nav-item"><strong>
                    <a class="nav-link text-info" href="{% url 'home:signup' %}">Sign UP</a>
                </strong></li>
     {% endif %}
               <li class="nav-item"><strong>
                    <a class="nav-link text-info" href="{% url 'home:contact' %}">contact me</a>
               </strong></li>
                <li class="nav-item"><strong>
                    <a class="nav-link text-info" href="{% url 'home:about' %}">about</a>
                </strong></li>
	{% if user.is_authenticated %}
            <li class="mav--item"><strong>
                  <a href="{% url 'store:cart' %}" class="notification text-info">
                     Cart <img  id="cart-icon" src="{% static 'images/cart.png' %}">
                     <span class="badge">{{cartItems}}</span>
                     </a></strong>
              </li>
	{% else %}
     	    <li class="mav--item"><strong>
                 <a class="nav-link text-info" href="#">Shit</a>
             </strong></li>
	{% endif %}
        </ul>
</nav>
 