Eshop/Eshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls import url
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    url(r'^', include('Home.urls', namespace='home')),
    url(r'^store/', include('store.urls', namespace='store')),
    url(r'^profile/', include('prof.urls', namespace='prof')),
]
handler404 = "Eshop.views.page_not_found_view"

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Eshop/Home/urls.py
from django.urls import path
from . import views
from django.contrib.auth import views as v_iews

app_name = 'Home'
urlpatterns = [
    path('', views.home, name='home'),
    path('contact', views.Contact, name='contact'),
    path('about/', views.about, name='about'),
    path('signup/', views.signup, name='signup'),
    path('login/', v_iews.LoginView.as_view(), name='login'),
    path('password_change/', v_iews.PasswordChangeView.as_view(), name='password_change'),
    path('password_change_done/', v_iews.PasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', v_iews.PasswordResetView.as_view(), name='password_reset'),
]

Eshop/store/urls.py
from django.urls import path, re_path
from django.conf.urls import url
from . import views

app_name = 'store'
urlpatterns = [
    url(r'^$', views.shop, name='menu'),
    path('product/<int:id>/', views.product, name='product'),
    path('category/<id>/', views.category, name='category'),
    path('cart/', views.cart, name='cart'),
    path('WishItems/', views.WishList, name='WishItems'),
    path('shipping/', views.shipping, name="shipping"),

    path('update_item/', views.updateItem, name="update_item"),
    path('add_to_wish_list/', views.addToWishList, name="addToWishList"),

    path('checkout/', views.checkout, name='checkout'),
    path('charge/', views.charge, name="charge"),
    path('success/<int:args>/', views.successMsg, name="success"),
    path('PaymentCompleted/', views.PaymentCompleted, name='PaymentCompleted')
]

Eshop/store/models.py
from django.db import models
from django.contrib.auth.models import User
from django.utils.text import slugify
from django.utils import timezone
import datetime
from django.db.models.signals import post_save
from django.conf import settings
from django_countries.fields import CountryField
from django.shortcuts import reverse
from phonenumber_field.modelfields import PhoneNumberField

PAYMENT_CHOICES = (
    ('S', 'Stripe'),
    ('P', 'Paypal')
)
CATEGORY = (
    ('SPORT', 'Sport Wear'),
    ('MEN', 'Men'),
    ('WOMEN', 'Women')
)
DELIVERY_CHOICES = (
    ('S', 'Standard'),
    ('P', 'Premium')
)
'''------Product-------'''
class Product(models.Model):
    name = models.CharField(max_length=50)
    category = models.CharField(choices=CATEGORY, max_length=8)
    description = models.TextField(default=' ')
    image = models.FileField(null=True, blank=True, upload_to='product/',max_length=500)
    price = models.FloatField()
    old_price = models.FloatField()
    item = models.PositiveIntegerField(default=1)
    def __str__(self):
        return self.name
'''---------Category---------- '''
class Categorys(models.Model):
    name = models.CharField(max_length=80)
    type = models.CharField(choices=CATEGORY,max_length=80)
    product = models.ForeignKey(Product, default=None,on_delete=models.CASCADE)
    def __str__(self):
        return self.name
'''-------Product images-------'''
class ProductImage(models.Model):
    product = models.ForeignKey(Product, default=None, on_delete=models.CASCADE)
    images = models.FileField(upload_to = 'product/', max_length=500)
    def __str__(self):
        return self.product.name

'''---------Order----------'''
class Order(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    date_ordered = models.DateTimeField(auto_now_add=True)
    complete = models.BooleanField(default=False)
    def __str__(self):
        if self.complete == True:
            return '%s Completed ----->' %(self.customer)
        else:
            return '%s Not Completed!! ------->' %(self.customer)
    @property
    def get_cart_total(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.get_total for item in orderitems])
        return total

    @property
    def get_cart_items(self):
        orderitems = self.orderitem_set.all()
        total = sum([item.quantity for item in orderitems])
        return total


'''---------Whish List -------------'''
class WishItem(models.Model):
    customer = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    date_added = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return '%s' %(self.customer)
    @property
    def get_total(self):
        wishitems = self.orderitem_set.all()
        total = sum([item.quantity for item in wishitems])
        return total

'''---------OrderItem---------'''
class OrderItem(models.Model):
    product = models.ForeignKey(Product, on_delete=models.SET_NULL, null=True)
    order = models.ForeignKey(Order, on_delete=models.SET_NULL, null=True)
    quantity = models.PositiveIntegerField(default=0, null=True, blank=True)
    date_added = models.DateTimeField(auto_now_add=True)

    @property
    def get_total(self):
        total = self.product.price * self.quantity
        return total
'''----------Shipping Address----------'''
class ShippingAddress(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE, related_name="questions")
    delivery_option = models.CharField(choices=DELIVERY_CHOICES, max_length=150)
    add1 = models.CharField(verbose_name="Addresse1", max_length=250)
    add2 = models.CharField(verbose_name="Addresse2", max_length=250)
    city = models.CharField(verbose_name="City", max_length=30)
    country = CountryField(multiple=False)
    number_phone = PhoneNumberField() # blank=True, null=False)
    zip_code = models.IntegerField(blank=False, null=True, verbose_name="Zip code")
    payment_option = models.CharField(choices=PAYMENT_CHOICES, max_length=1)
    slug = models.SlugField(null=True, blank=True)
    def __str__(self):
        return '%s' %(self.user)
    def save(self, *args, **kwargs):
        if not self.slug:
            self.slug = slugify(self.user.username)
        super(ShippingAddress, self).save(*args, **kwargs)

#    def __str__(self):
#        return '%s' %(self.user)

def create_profile(sender, **kwargs):
        if kwargs['created']:
            customer_adress = ShippingAddress.objects.create(user=kwargs['instance'])

post_save.connect(create_profile, sender=User)

Eshop/store/forms.py
from django import forms
from .models import ShippingAddress
from django_countries.fields import CountryField
from phonenumber_field.formfields import PhoneNumberField

PAYMENT_CHOICES = (
    ('S', 'Stripe'),
    ('P', 'Paypal')
)
DELIVERY_CHOICES = (
    ('S', 'Standard'),
    ('P', 'Premium')
)

class ShippingForm(forms.ModelForm):
    add1 = forms.CharField(label='Addresse1 :', widget=forms.TextInput(attrs={'placeholder':'1234 Main St'}))
    add2 = forms.CharField(label='Addresse2 :', widget=forms.TextInput(attrs={'placeholder':'Apartment or suite'}))
    number_phone = PhoneNumberField(label='Phone Number :', widget=forms.TextInput(attrs={'placeholder':'Phone Number us +xxx'}))
    country = CountryField(blank_label='Select country').formfield()
    zip_code = forms.CharField(label='Zip code :', widget=forms.TextInput(attrs={'placeholder':'Zip Code'}))
    city = forms.CharField(label='City :', widget=forms.TextInput(attrs={'placeholder': 'City'}))
    payment_option = forms.ChoiceField(widget=forms.RadioSelect, choices=PAYMENT_CHOICES, initial='S')
    delivery_option = forms.ChoiceField(widget=forms.RadioSelect, choices=DELIVERY_CHOICES, initial='S')
    class Meta:
        model = ShippingAddress
        fields = ['add1', 'delivery_option', 'add2', 'city', 'country', 'number_phone', 'zip_code', 'payment_option']

Eshop/store/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import JsonResponse, HttpResponseRedirect
from .models import *
from django.contrib import messages
from django.urls import reverse
import stripe
import json
from store.forms import ShippingForm
from django.contrib.auth.decorators import login_required

stripe.api_key = 'sk_test_51JKPAME9Zu8rS7a9XlPIVZy6EEMx39b4UeYQVxhhCqih8iLorshvhTmMEFVFHQWBUVfXQN14ZE3UP8lCNe8fXbrp001BLCzuIR'

def category(request, id):
    category = Product.objects.all()

    product = get_object_or_404(Product, category=id)
    id = product.category
#    category = Product.objects.get(category=id)
#    if category == id:
#        category.category = id
    context = {
        'id': id,
        'category': category,
    }
    return render(request, 'store/category.html', context)

def checkout(request):
    form = get_object_or_404(ShippingAddress, user=request.user)

    customer = request.user
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    items = order.orderitem_set.all()
    cartItems = order.get_cart_items
    context = {
        'form': form,
        'order': order,
    }
    return render(request, 'store/checkout.html', context)
def charge(request):
    if request.method == 'POST':
        try:
            print('Data:', request.POST)
            customer = request.user
            order, created = Order.objects.get_or_create(customer=customer, complete=False)
            items = order.orderitem_set.all()
            cartItems = order.get_cart_items

            form = get_object_or_404(ShippingAddress, user=request.user)
            price = float(order.get_cart_total)
            amount = int(price*100)
            number_phone = form.number_phone
            customer = stripe.Customer.create(
            phone=number_phone,
                email=request.user.email,
                name=form.user,
                source=request.POST['stripeToken']
            )

            charge = stripe.Charge.create(
                customer=customer,
                amount=amount,
                currency='usd',
                description="Shoping"
            )
            Order.objects.get_or_create(customer=customer, complete=True)
        except stripe.error.CardError as e:
            body = e.json_body
            err = body.get('error', {})
            messages.error(self.request, f"{err.get('message')}")
            return redirect('store:menu')
        except stripe.error.APIConnectionError as e:
            messages.error(request, "Network Error")
            return redirect('store:menu')
        except Exception as e:
            # Something else happened, completely unrelated to Stripe
            messages.error(request, "Not identified error")
            return redirect('store:menu')
    return redirect(reverse('store:success', args=[amount]))


def successMsg(request, args):
        '''sucess payment'''
        amount = args
        price = int(args/100)

        context = {
                'price': price,
        }
        return render(request, 'store/success.html', context)

def PaymentCompleted(request):
    body = json.loads(request.body)
    print("BODY: ",body)
    customer = request.user
#    product = Product.objects.get(id=body['productID'])
    Order.objects.create(
        customer=request.user,
        complete=True
    )
    return JsonResponse('Payment Completed', safe=False)

def shop(request):
    if request.user.is_authenticated:
        customer = request.user
        order, created = Order.objects.get_or_create(customer=customer, complete=False)
        items = order.orderitem_set.all()
        cartItems = order.get_cart_items
    else:
        cartItems = 0
        items = 0
        order = 0
#        data = json.loads(request.body)
#        action = data['action']
#        print('Action:', action)

    products = Product.objects.all()
    context = {
        'products': products,
	'cartItems': cartItems,
	'items': items,
	'order': order,
    }
    return render(request, 'store/menu.html', context)

@login_required
def cart(request):
    check = get_object_or_404(ShippingAddress, user=request.user)
    form = ShippingForm(request.POST or None, instance=check)
    if request.method == 'POST':
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            messages.success(request, 'Some User Add Shipping Address ✔️')
            return redirect(reverse('store:checkout'))
        else:
            print('-------------------> Somthing Else :)')
            form = ShippingForm(request.POST or None)

    customer = request.user
    order, created = Order.objects.get_or_create(customer=customer, complete=False)
    items = order.orderitem_set.all()
    cartItems = order.get_cart_items

    context = {
        'cartItems': cartItems,
        'items': items,
        'order': order,
        'form': form
    }
    return render(request, 'store/cart2.html', context)

def updateItem(request):
        data = json.loads(request.body)
        productId = data['productId']
        action = data['action']
        print('Action:', action)
        print('Product:', productId)

        customer = request.user
        product = Product.objects.get(id=productId)
        order, created = Order.objects.get_or_create(customer=customer, complete=False)

        orderItem, created = OrderItem.objects.get_or_create(order=order, product=product)

        if action == 'add':
                orderItem.quantity = (orderItem.quantity + 1)
        elif action == 'remove':
                orderItem.quantity = (orderItem.quantity - 1)

        orderItem.save()

        if orderItem.quantity <= 0:
                orderItem.delete()

        return JsonResponse('Item was added', safe=False)
def addToWishList(request):
    data = json.loads(request.body)
    productId = data['productId']
    action = data['action']
    print('Action:', action)
    print('Product:', productId)

    customer = request.user
    product = Product.objects.get(id=productId)

    wishItem, created = WishItem.objects.get_or_create(customer=customer, product=productId)

    if action == 'add':
        wishItem.quantity = (wishItem.quantity + 1)
    elif action == 'remove':
        wishItem.quantity = (wishItem.quantity - 1)

    wishItem.save()

    if wishItem.quantity <= 0:
        wishItem.delete()

    return JsonResponse('Item was added To Wish List', safe=False)

def WishList(request):
    data = json.loads(request.body)
    productId = data['productId']
    product = Product.objects.get(id=productId)
    customer = request.user

    wishItem, created = WishItem.objects.get_or_create(customer=customer, product=product)
    items = wishItem.orderitem_set.all()
    cartItems = wishItem.get_total

    context = {
	'wishItem': wishItem,
	'items': items,
	'cartItems': cartItems
	}
    return render(request, 'store/wish.html', context)

def product(request, id):
    product = get_object_or_404(Product, id=id)
    photos = ProductImage.objects.filter(product=product)
    context = {
            'product': product,
            'photos': photos,
        }
    return render(request, 'store/product.html', context)

@login_required
def shipping(request):

    form = ShippingForm(request.POST or None, instance=check)

    if request.method == 'POST':
        if form.is_valid():
            new_form = form.save(commit=False)
            new_form.user = request.user
            new_form.save()
            messages.success(request, 'Some User Add Shipping Address ✔️')
            return redirect(reverse('store:checkout'))
        else:
            form = ShippingForm(request.POST or None)
    context = {
        'check': check,
        'form': form,
         'order': order
    }
    return render(request, 'store/checkout.html', context)

Eshop/templates/store/cartEmpty.html
{% load static %}
<style>
.mt-100 {
    margin-top: 100px
}

.card {
    margin-bottom: 30px;
    border: 0;
    -webkit-transition: all .3s ease;
    transition: all .3s ease;
    letter-spacing: .5px;
    border-radius: 8px;
    -webkit-box-shadow: 1px 5px 24px 0 rgba(68, 102, 242, .05);
    box-shadow: 1px 5px 24px 0 rgba(68, 102, 242, .05)
}

.card .card-header {
    background-color: #fff;
    border-bottom: none;
    padding: 24px;
    border-bottom: 1px solid #f6f7fb;
    border-top-left-radius: 8px;
    border-top-right-radius: 8px
}

.card-header:first-child {
    border-radius: calc(.25rem - 1px) calc(.25rem - 1px) 0 0
}

.card .card-body {
    padding: 30px;
    background-color: transparent
}

.btn-primary,
.btn-primary.disabled,
.btn-primary:disabled {
    background-color: #4466f2 !important;
    border-color: #4466f2 !important
}
.mg {
  height: 20rem;
  width: 20rem;
}
@media(max-width:767.98px){
  .mg {
    height: 9rem;
    width: 10rem;
}
}
</style>    

<div class="container-fluid mt-100">
  <div class="row">
     <div class="col-md-12">
      <div class="card">
        <div class="card-header">
          <h3>Cart: </h3>
        </div>
        <div class="card-body cart">
          <div class="col-sm-12 empty-cart-cls text-center">
            <img src="{% static 'images/CartEmpty.png' %}" class="mg" loading="lazy">
            <h3><strong>Your Cart is Empty</strong></h3>
             <h4>Please Add a Few Product :)</h4>
            <a href="{% url 'store:menu' %}" class="btn btn-primary cart-btn-transform m-3" data-abc="true">Back To Store</a>
            </div>
          </div>
        </div>
      </div>
    </div>
 </div>

Eshop/templates/store/category.html
{% extends "base.html" %}

{% block content %}
{% include "navbar.html" %}

{% for categorys in category %}

{% if categorys.category == id %}

   <h1 class="text-secondary">{{ categorys.category }}</h1>
 {{ categorys.name }}
<br>
 {{ categorys.description }}
 <br>
  {{ categorys.price }}

{% else %}

Not Category Available Here...

{% endif %}

{% endfor %}

{% include "footer.html" %}
{% endblock %}

Eshop/templates/store/checkout.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block title %}E-shop: Checkout{% endblock %}
{% block content %}
<main >
    <div class="container wow fadeIn">

 
      <h2 class="my-5 h2 text-center">Checkout form</h2>

          <!-- Cart -->
          <ul class="list-group mb-3 z-depth-1">
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Ship To: </h6>
                <small class="text-muted">{{ form.country }} {{ form.city }} {{ form.add1 }}<br>
		 {{ form.add2 }} {{ form.zip_code }}</small>
              </div>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Items:</h6>
                <small class="text-muted">{{order.get_cart_items}} items</small>
              </div>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Delivery Type:</h6>
                <small class="text-muted"></small>
              </div>
              <span class="text-muted">{{ o }}</span>
            </li>
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (USD)</span>
              <strong>$ {{order.get_cart_total|floatformat:2}}</strong>
            </li>
          </ul>

{% if form.payment_option == "S" %}
      <!------------ Stripe --------------->
   {% include 'store/stripe.html' %}
     <!--------- End Stripe Form ----------->
{% else %}
          <!-------- Paypal Smart Button -------->
                {% include 'store/paypal.html' %}
          <!------- End paypal Button----------->
{% endif %}
        </div>
      </div>
    </div>
  </main>
{% include "footer.html" %}
{% endblock content %}

Eshop/templates/store/menu.html
{% extends 'base.html' %}
{% load static %}
{% block title %}E-shop{% endblock %}
{% block content %}

<style>
button {
    border-radius: 50px;
}
.add-btn {
  border-radius: 50rem;
  color: black;
}
.container {
  max-width: 100%;
  margin: auto;
}
</style>
{% include "navbar.html" %}
<!--   END NAV BAR -->

<!--<main role="main">
  <!--<section class="jumbotron text-center bg-light">-->
       <img src="{% static 'images/open.png' %}" class="imagg" alt="interface" loading="lazy">

  <!--</section--> 
<!-- end section ............-->

{% if products %}

<div class="album py-5 bg-light">
 <div class="container">
  <div class="row">
{% for product in products %}
      <div class="col-md-4">
        <div class="card sh300 mb-4 shadow-sm">
           <div class="card-body sh300">

             <img class="icone21" src="{{ product.image.url }}" loading="lazy">
           <h4 class="text-dark text-muted">{{ product.name }}</h4>
        <a href="{% url 'store:product' id=product.id %}" class="btn btn1">View</a>
      <button data-product="{{ product.id}} " data-action="add" class="add-btn btn btn-info cart-btn-transform m-3 update-cart">+ <i class="fas fa-shopping-cart"></i></button>
     <!--
            <h4 class="card-text text-light">{{ products.description | truncatewords:5 }}</h4>
      -->
       <!--<h4 style="display: inline-block; float: right;">-->
         <strong class="waw"> ${{ product.price }}</strong>

        </div>
        </div>
      </div>
{% endfor %}
     </div>
   </div>
</div>
</main>
{% else %}
<br>
<br>
<h1 class="text-info text-center">Sorry!!</h1>
<br>
<h3 class="text-center text-primary">No Product Available Now<br>
  <p>Please try in next time</p>
</h3>
{% endif %}
{% include "footer.html" %}

{% endblock %}

Eshop/templates/store/paypal.html
{% load static %}
<!-- Paypal -->
<script src="https://www.paypal.com/sdk/js?client-id=AXKJa6Y25vxVUVIdn2xVbqvh6OHK5k1Z1nJ0TL19KRsfQkWlnirp6qMaQYdHrKWSoAL9uduoom0RnKgW&disable-funding=credit,card&currency=USD" data-sdk-integration-source="button-factory"></script>
                <div id="smart-button-container">
                  <div style="text-align: center;">
                    <div id="paypal-button-container"></div>
                  </div>
                </div>
  <script>
    function getCookie(name) {
        let cookieValue = null;
        if (document.cookie && document.cookie !== '') {
            const cookies = document.cookie.split(';');
            for (let i = 0; i < cookies.length; i++) {
                const cookie = cookies[i].trim();
                // Does this cookie string begin with the name we want?
                if (cookie.substring(0, name.length + 1) === (name + '=')) {
                    cookieValue = decodeURIComponent(cookie.substring(name.length + 1));
                    break;
                }
            }
        }
        return cookieValue;
    }

    const csrftoken = getCookie("csrftoken");
    var total = "{{order.get_cart_total|floatformat:2}}";
    var productID = "{{ product.id }}";

    function completeOrder(){
        var url = "{% url 'store:PaymentCompleted' %}";

        fetch(url, {
            method: 'POST',
            headers: {
                'Content-type': 'application/json',
                'X-CSRFToken': csrftoken,
            },
            body: JSON.stringify({'productID': productID}),
        })
    }
    function initPayPalButton() {
      paypal.Buttons({
        style: {
          shape: 'pill',
          color: 'blue',
          layout: 'vertical',
          label: 'checkout',
        },

        createOrder: function(data, actions) {
          return actions.order.create({
            purchase_units: [{"amount":{"currency_code":"USD","value":total}}]
          });
        },
        onApprove: function(data, actions) {
          return actions.order.capture().then(function(orderData) {

            // Full available details
            console.log('Capture result', orderData, JSON.stringify(orderData, null, 2));
            completeOrder()
            // Show a success message within this page, e.g.
            const element = document.getElementById('paypal-button-container');
            element.innerHTML = '';
            element.innerHTML = '<h3>Thank you for your payment!</h3>' + details.payer.now.given_name + '!';
            actions.redirect('success.html');

          });
        },

        onError: function(err) {
          console.log(err);
        }
      }).render('#paypal-button-container');
    }
    initPayPalButton();
</script>
          <!-- End paypal Button-->

Eshop/templates/store/stripe.html
{% extends "base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<!doctype html>
<html>
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">

  <title data-tid="elements_examples.meta.title">Stripe Elements: Build beautiful, smart checkout flows</title>
  <meta data-tid="elements_examples.meta.description" name="description" content="Build beautiful, smart checkout flows.">
  <style>
  input {
  border-radius: 6px;
  margin-bottom: 6px;
  padding: 12px;
  border: 1px solid rgba(50, 50, 93, 0.1);
  height: 44px;
  font-size: 16px;
  width: 100%;
  background: white;
}

.result-message {
  line-height: 22px;
  font-size: 16px;
}

.result-message a {
  color: rgb(89, 111, 214);
  font-weight: 600;
  text-decoration: none;
}

.hidden {
  display: none;
}

#card-error {
  color: rgb(105, 115, 134);
  text-align: left;
  font-size: 13px;
  line-height: 17px;
  margin-top: 12px;
}

#card-element {
  border-radius: 4px 4px 0 0 ;
  padding: 12px;
  border: 1px solid rgba(50, 50, 93, 0.1);
  height: 44px;
  width: 100%;
  background: white;
}
        /* Blue outline on focus */
.StripeElement--focus {
            border-color: #80BDFF;
            outline:0;
            box-shadow: 0 0 0 .2rem rgba(0,123,255,.25);
            transition: border-color .15s ease-in-out, box-shadow .15s ease-in-out;
}
        /* Can't see what I type without this */
#card-number.form-control,
#card-cvc.form-control,
#card-exp.form-control {
            display:inline-block;
}
  </style>
</head>

<!--Stripe Form-->
<script src="https://js.stripe.com/v3/"></script>
<form action="{% url 'store:charge' %}" method="post" id="payment-form">
   {% csrf_token %}
    <div class="form-row">
      <label for="card-element">
        Credit or debit card
      </label>
      <div id="card-element">
        <!-- A Stripe Element will be inserted here. -->
      </div>
      <!-- Used to display form errors. -->
      <div id="card-errors" role="alert"></div>
      </div>
      <div style="clear:left"></div>
        <br>
    <button class="btn btn-secondary btn-block" id="test_checkout-button" type="submit">Continue To Checkout</button>
</form>
<br>
<script>
// Create a Stripe client
		//var url = "";
                var product_ID = "{{ product.id }}";
                var stripe = Stripe("pk_test_51JKPAME9Zu8rS7a9ffycJWJEV2p3Tds4wKaYXmgBsSniQi0RBZwxNcYkhhaccDWXBZ5MuDjyBAk7FTwYuwo6oyv900l2UOIIM6");
                
		//function completeOrder(){
        	//fetch(url, {
            	//	method: 'POST',
            	//		headers: {
                //			'Content-type': 'application/json',
                //			'X-CSRFToken': csrftoken,
            	//			},
            	//		body: JSON.stringify({'productID': productID}),
        	//		})
    		//}

                // Create an instance of Elements.
                var elements = stripe.elements();

                // Custom styling can be passed to options when creating an Element.
                // (Note that this demo uses a wider set of styles than the guide below.)
                var style = {
                  base: {
                    color: '#32325d',
                    fontFamily: '"Helvetica Neue", Helvetica, sans-serif',
                    fontSmoothing: 'antialiased',
                    fontSize: '16px',
                    '::placeholder': {
                      color: '#aab7c4'
                    }
                  },
                  invalid: {
                    color: '#fa755a',
                    iconColor: '#fa755a'
                  }
                };

                // Create an instance of the card Element.
                var card = elements.create('card', {style: style});

                // Add an instance of the card Element into the `card-element` <div>.
                card.mount('#card-element');

                // Handle real-time validation errors from the card Element.
                card.addEventListener('change', function(event) {
                  var displayError = document.getElementById('card-errors');
                  if (event.error) {
                    displayError.textContent = event.error.message;
                  } else {
                    displayError.textContent = '';
                  }
                });

                // Handle form submission.
                var form = document.getElementById('payment-form');
                form.addEventListener('submit', function(event) {
                  event.preventDefault();

                  stripe.createToken(card).then(function(result) {
                    if (result.error) {
                      // Inform the user if there was an error.
                      var errorElement = document.getElementById('card-errors');
                      errorElement.textContent = result.error.message;
                    } else {
                      // Send the token to your server.
                      stripeTokenHandler(result.token);
                    }
                  });
                });

                // Submit the form with the token ID.
                function stripeTokenHandler(token) {
                  // Insert the token ID into the form so it gets submitted to the server
                  var form = document.getElementById('payment-form');
                  var hiddenInput = document.createElement('input');
                  hiddenInput.setAttribute('type', 'hidden');
                  hiddenInput.setAttribute('name', 'stripeToken');
                  hiddenInput.setAttribute('value', token.id);
                  form.appendChild(hiddenInput);

                  // Submit the form
                  form.submit();
		  //completeOrder()
                }
</script>
        <!--End stripe Form-->
{% endblock %}

Eshop/templates/store/wish.html
{% extends 'base.html' %}
{% load static %}
{% block title %}Cart: all items{% endblock %}
{% block content %}

{% include "navbar.html" %}
<br>
{% if items %}
 {{ cartItems }}
{% for item in items %}

	{{item.product.name}}

	{{item.get_total|floatformat:2}}
{% endfor %}


{% else %}
no Items to Your Wish List Items
{% endif %}



{% endblock %}